steps:
- name: node:16.13.2
  entrypoint: npm
  args: ["install"]
- name: node:16.13.2
  entrypoint: npm
  args: ["run", "start"]
  env:
    - 'MONGO_USER=${_MONGO_USER}'
    - 'MONGO_PASS=${_MONGO_PASS}'
    - 'MONGO_URL=${_MONGO_URL}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
